package com.bci.productcrud.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "goods_received_notes")
@Getter
@Setter
@NoArgsConstructor
public class GoodsReceivedNote {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Auto-generated by the service (GRN-0001) from the DB id — not part of the request body. */
    @Column(unique = true)
    private String grnNumber;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "purchase_order_id", nullable = false)
    private PurchaseOrder purchaseOrder;

    @Column(nullable = false)
    private LocalDate receivedDate;

    private String receivedBy;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private GrnStatus status = GrnStatus.DRAFT;

    @Column(nullable = false)
    private Integer totalReceivedQuantity = 0;

    @Column(length = 1000)
    private String notes;

    @OneToMany(mappedBy = "goodsReceivedNote", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<GoodsReceivedNoteItem> items = new ArrayList<>();

    /** Optimistic lock — protects against two simultaneous confirmations double-updating stock. */
    @Version
    private Long version;

    @Column(updatable = false)
    private Instant createdAt;

    private Instant updatedAt;

    @PrePersist
    void onCreate() {
        createdAt = Instant.now();
        updatedAt = createdAt;
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = Instant.now();
    }

    public void addItem(GoodsReceivedNoteItem item) {
        items.add(item);
        item.setGoodsReceivedNote(this);
    }
}
